version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm run build
      - ls -a

  post_build:
    commands:
      - aws s3 sync out/ s3://$BUCKETNAME
      - aws cloudfront create-invalidation --distribution-id $CF_DISTRIBUTION_ID --paths "/*"
