import 'ag-grid-community/styles//ag-grid.css';
import 'ag-grid-community/styles//ag-theme-alpine.css';
import './globals.css'
import '../assets/scss/index.scss';
import '../assets/fonts/css/general-sans.css';
import type { Metadata } from 'next'
import Providers from './provider';

export const metadata: Metadata = {
  title: 'Axiom Admin',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
