export const FORMIK_REGEX = {
  PASSWORD_REGEX:
    /^.*(?=.{6})((?=.*[!@#$%^&*()\-_=+{};:,<.>]){1})(?=.*\d)((?=.*[a-z]){1})((?=.*[A-Z]){1}).*$/,
  BRAND_NAME: /^[A-Za-z0-9]+[A-Za-z0-9\s!@#$%^&*()-]*$/,
  TEXT: /^[a-zA-Z0-9_ ]*$/,
  NUMBER: /^[0-9]$/,
  EMAIL_REGEX: /^[A-Z0-9.]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i,
  ALPHA_REGEX: /^[a-zA-Z]+$/,
};

export const RESPONSE_CODE = {
  STATUS_SUCCESSFUL: 201,
  STATUS_OK: 200,
  STATUS_BAD_REQUEST: 400,
  STATUS_UNAUTHORISED: 401,
  STATUS_NOT_FOUND: 404,
  STATUS_UNPROCESSIBLE_CONTENT: 422,
  STATUS_INTERNAL_SERVER_ERROR: 500,
};

export const PAGE_ROUTE_LOCATION = {
  CUSTOMERS:"customers",
  CUSTOMERDATA:"customerData",
  DASHBOARD:"dashboard",
  INVOICES:"invoices",
  REQUESTS:"requests"
};

export const TRAILSLASH = '/';
export const MESSAGES = {};

export const DASHBOARD_MESSAGE = {
  DATA_NOT_FOUND: "No Data to Display",
};

export const ROLE = {
  USER: "user"
}

export const stackName = "axiomio";

export const templateURL =
  "https://aiops-cft.s3.amazonaws.com/AIOPS_ManagementAccount_template.json";

export const TOKEN_EXPIRED_TEXT = "Token is expired";

export const AWS_ACCOUNT_FIELD_INFO =
  "Enter the AWS Account Alias or Friendly Name. This user-defined name helps identify the account within this portal.";
export const AWS_ARN_FIELD_INFO =
  "Provide the IAM Role ARN generated by the CloudFormation Template. This role defines permissions within your AWS environment.";
export const TEST_SITE_KEY = "0x4AAAAAAAIgTw0b_y4t3XQp";

export const ACCOUNT_TYPE = {
  management_account : 'management_account'
}

export const REQUEST_STATUS = {
  PENDING: 'pending',
  COMPLETED: 'completed',
  CLOSED: 'closed',
  INPROGRESS: 'in-progress',
  CANCELLED: 'cancelled',
  OPEN: 'open'
}

export const ACCOUNT = {
  aws: 'aws',
  azure: 'azure',
}

export const INVOICES_STATUS = {
  ISSUED: 'issued',
  OVERDUE: 'overdue',
  PAID: 'paid' 
}

export const FUTURE_SCOPE = "coming soon...";